image: docker:stable
stages:
  - package
  - docker_build
  - deploy_k8s
variables:
  KUBECNFIG: /etc/deploy/config
docker_build_job:
  tags:
    - gitlab-runner
  
  script:
    - docker login -u $REGISTRY_USERNAME -p $REGISTRY_PASSWORD # hub.docker.com
    - docker build -t gitlab-ci-test:$CI_PIPELINE_ID .
    - docker push gitlab-ci-test:$CI_PIPELINE_ID
